name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: maths-house

      - name: Verify Raw assets are present (LFS/media)
        run: |
          set -e
          echo "Listing Assets/Raw contents:" 
          ls -lah ../Assets/Raw || true
          for f in ZStartingVideo.mp4 evilwitch.wav i18n.en.json responsive_layout.json; do
            if [ -f ../Assets/Raw/$f ]; then
              echo "OK: ../Assets/Raw/$f exists"
            else
              echo "WARN: ../Assets/Raw/$f NOT FOUND" >&2
            fi
          done
        working-directory: maths-house

      - name: Build Angular (Pages base-href)
        run: |
          npm run build -- --base-href "/MathsHouseAngular20/"
        working-directory: maths-house

      - name: Determine output dir and add SPA 404
        id: outdir
        run: |
          set -e
          if [ -f dist/maths-house/index.html ]; then
            OUT="dist/maths-house"
          elif [ -f dist/maths-house/browser/index.html ]; then
            OUT="dist/maths-house/browser"
          else
            echo "Index.html not found. Tree:" >&2
            ls -R dist || true
            exit 1
          fi
          echo "Using output: $OUT"
          cp "$OUT/index.html" "$OUT/404.html"
          echo "out=$OUT" >> "$GITHUB_OUTPUT"
        working-directory: maths-house

      - name: Verify built assets exist in output
        run: |
          set -e
          OUT="${{ steps.outdir.outputs.out }}"
          echo "Listing $OUT/assets/video and $OUT/assets/audio:"
          ls -lah "$OUT/assets/video" || true
          ls -lah "$OUT/assets/audio" || true
          if [ -f "$OUT/assets/video/ZStartingVideo.mp4" ]; then echo OK: video present; else echo WARN: video missing; fi
          if [ -f "$OUT/assets/audio/evilwitch.wav" ]; then echo OK: audio present; else echo WARN: audio missing; fi
          echo "Listing $OUT/assets/Raw for responsive_layout.json:"
          ls -lah "$OUT/assets/Raw" || true
          if [ -f "$OUT/assets/Raw/responsive_layout.json" ]; then echo OK: responsive_layout present; else echo WARN: responsive_layout missing; fi
        working-directory: maths-house

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: maths-house/${{ steps.outdir.outputs.out }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
